### ISSUE TITLE
Could not resolve airline theme "tomorrow".

### ISSUE THREAD

**Issue by nertzy** [pivotal/vim-config#1]
Seeing this when I start MacVim:

> Could not resolve airline theme "tomorrow". Themes have been migrated to github.com/vim-airline/vim-airline-themes.

**Comment by diegodesouza** [comment]
@nertzy did you figure what the issue was?

**Comment by nertzy** [comment]
Yes. The airline repo had moved, and themes were extracted into a separate repo.

Fixed by ca5b96db647255145fe84f59d2355f947c4e846a
